# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 15:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0092_auto_20170327_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flowstart',
            name='contact_count',
        ),
    ]
