# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-14 21:17
from __future__ import unicode_literals, print_function

from django.db import migrations


def backfill_flow_sessions(apps, schema_editor):
    FlowSession = apps.get_model('flows', 'FlowSession')
    ChannelSession = apps.get_model('channels', 'ChannelSession')

    channel_sessions = list(ChannelSession.objects.filter(flow_session=None))
    if not channel_sessions:
        return

    print("Fetched %d channel sessions which need flow sessions" % len(channel_sessions))

    num_created = 0
    for ch_session in channel_sessions:
        FlowSession.objects.create(org=ch_session.org, contact=ch_session.contact,
                                   session_type=ch_session.session_type, channel_session=ch_session)
        num_created += 1

        if num_created % 1000 == 0:
            print(" > Created flow sessions for %d of %d channel sessions" % (num_created, len(channel_sessions)))


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0111_flowsession'),
    ]

    operations = [
        migrations.RunPython(backfill_flow_sessions)

    ]
